# coding: utf-8

# データを追加したらrake db:seedを実行
# data set
MessageContent.create(:name => "トイ太郎", :sex => "男", :mood => "普通", :person_type => "秘密", :content => "疲れ気味なので3階で寝まてます。")
MessageContent.create(:name => "田中", :sex => "男", :mood => "お話したい", :person_type => "女装", :content => "来ちゃった！")
MessageContent.create(:name => "森田", :sex => "男", :mood => "疲れ気味", :person_type => "女装", :content => "21時ごろ行きます。")
MessageContent.create(:name => "みちょぱ", :sex => "NH", :mood => "普通", :person_type => "秘密", :content => "朝までいるよ〜")
MessageContent.create(:name => "りさ子", :sex => "男の娘", :mood => "ムラムラ", :person_type => "女装", :content => "今日は泊まりです。")
MessageContent.create(:name => "ヒゲ男", :sex => "女装", :mood => "お話したい", :person_type => "秘密", :content => "初めて行きます。よろしくお願いします。")
MessageContent.create(:name => "モン太", :sex => "女装", :mood => "普通", :person_type => "女装", :content => "差し入れ持って行きます。")
MessageContent.create(:name => "純男", :sex => "男", :mood => "秘密", :person_type => "秘密", :content => "終電逃したので行きます。")
MessageContent.create(:name => "とっちゃん", :sex => "男", :mood => "普通", :person_type => "秘密", :content => "2階は満員御礼。")
MessageContent.create(:name => "12345", :sex => "秘密", :mood => "秘密", :person_type => "秘密", :content => "3日連続でいます。")
MessageContent.create(:name => "純男2", :sex => "男", :mood => "秘密", :person_type => "秘密", :content => "23時ごろ向かいます。")
MessageContent.create(:name => "まぐろ", :sex => "男", :mood => "普通", :person_type => "秘密", :content => "お刺身持っていきます。")
MessageContent.create(:name => "純男", :sex => "男", :mood => "秘密", :person_type => "秘密", :content => "またきたよ。")
MessageContent.create(:name => "とっちゃん", :sex => "男", :mood => "普通", :person_type => "秘密", :content => "2階でまったり")
MessageContent.create(:name => "12345", :sex => "秘密", :mood => "秘密", :person_type => "秘密", :content => "6日連続でいます。")
MessageContent.create(:name => "純男2", :sex => "男", :mood => "秘密", :person_type => "秘密", :content => "21時ごろ向かいます。")
MessageContent.create(:name => "まぐろ", :sex => "男", :mood => "普通", :person_type => "秘密", :content => "お昼頃から外出します")
MessageContent.create(:name => "純男", :sex => "男", :mood => "秘密", :person_type => "秘密", :content => "始発で帰ります。")
MessageContent.create(:name => "とっちゃん", :sex => "男", :mood => "普通", :person_type => "秘密", :content => "2階は過疎ってます。")
MessageContent.create(:name => "12345", :sex => "秘密", :mood => "秘密", :person_type => "秘密", :content => "3階で寝待ち...")
MessageContent.create(:name => "純男2", :sex => "男", :mood => "秘密", :person_type => "秘密", :content => "19時に帰ります")
MessageContent.create(:name => "まぐろ", :sex => "男", :mood => "普通", :person_type => "秘密", :content => "東京から来ました。仲良くして下さい。")
